overall_columns = ("Type", "Sex", "Deaths", "Death Rate", "Year", "Population Type")
specific_columns = ("Drug Type", "Sex", "with/without?", "Opioid Type", "Deaths", "Death Rate", "Year", "Population Type")
demographic_columns = ()

config = {
    'Number Drug OD Deaths': {
        "valid_rows": 103,
        "indices": {
            ("Overall", "Female"): 1,
            ("Overall", "Male"): 2,
            ("Any opioid", "Female"): 4,
            ("Any opioid", "Male"): 5,
            ("Prescription opioids", "Female", "overall", "overall"): 8,
            ("Prescription opioids", "Male", "overall", "overall"): 9,
            ("Prescription opioids", "Female", "with", "synthetic"): 11,
            ("Prescription opioids", "Male", "with", "synthetic"): 12,
            ("Synthetic opioids", "Female", "overall", "overall"): 17,
            ("Synthetic opioids", "Male", "overall", "overall"): 18,
            ("Heroin", "Female", "overall", "overall"): 20,
            ("Heroin", "Male", "overall", "overall"): 21,
            ("Heroin", "Female", "with", "synthetic"): 23,
            ("Heroin", "Male", "with", "synthetic"): 24,
            ("Stimulants", "Female", "overall", "overall"): 29,
            ("Stimulants", "Male", "overall", "overall"): 30,
            ("Stimulants", "Female", "with", "any"): 32,
            ("Stimulants", "Male", "with", "any"): 33,
            ("Stimulants", "Female", "with", "synthetic"): 38,
            ("Stimulants", "Male", "with", "synthetic"): 39,
            ("Cocaine", "Female", "overall", "overall"): 44,
            ("Cocaine", "Male", "overall", "overall"): 45,
            ("Cocaine", "Female", "with", "any"): 47,
            ("Cocaine", "Male", "with", "any"): 48,
            ("Cocaine", "Female", "with", "synthetic"): 53,
            ("Cocaine", "Male", "with", "synthetic"): 54,
            ("Psychostimulants", "Female", "overall", "overall"): 59,
            ("Psychostimulants", "Male", "overall", "overall"): 60,
            ("Psychostimulants", "Female", "with", "any"): 62,
            ("Psychostimulants", "Male", "with", "any"): 63,
            ("Psychostimulants", "Female", "with", "synthetic"): 68,
            ("Psychostimulants", "Male", "with", "synthetic"): 69,
            ("Benzodiazepines", "Female", "overall", "overall"): 74,
            ("Benzodiazepines", "Male", "overall", "overall"): 75,
            ("Benzodiazepines", "Female", "with", "any"): 77,
            ("Benzodiazepines", "Male", "with", "any"): 78,
            ("Benzodiazepines", "Female", "with", "synthetic"): 83,
            ("Benzodiazepines", "Male", "with", "synthetic"): 84,
            ("Antidepressants", "Female", "overall", "overall"): 89,
            ("Antidepressants", "Male", "overall", "overall"): 90,
            ("Antidepressants", "Female", "with", "any"): 92,
            ("Antidepressants", "Male", "with", "any"): 93,
            ("Antidepressants", "Female", "with", "synthetic"): 98,
            ("Antidepressants", "Male", "with", "synthetic"): 99,
        }


    },
    'Rate Drug OD Deaths': {
        "valid_rows": 102,
        "indices": {
            ("Overall", "Female"): 1,
            ("Overall", "Male"): 2,
            ("Any opioid", "Female"): 4,
            ("Any opioid", "Male"): 5,
            ("Prescription opioids", "Female", "overall", "overall"): 7,
            ("Prescription opioids", "Male", "overall", "overall"): 8,
            ("Prescription opioids", "Female", "with", "synthetic"): 10,
            ("Prescription opioids", "Male", "with", "synthetic"): 11,
            ("Synthetic opioids", "Female", "overall", "overall"): 16,
            ("Synthetic opioids", "Male", "overall", "overall"): 17,
            ("Heroin", "Female", "overall", "overall"): 19,
            ("Heroin", "Male", "overall", "overall"): 20,
            ("Heroin", "Female", "with", "synthetic"): 22,
            ("Heroin", "Male", "with", "synthetic"): 23,
            ("Stimulants", "Female", "overall", "overall"): 28,
            ("Stimulants", "Male", "overall", "overall"): 29,
            ("Stimulants", "Female", "with", "any"): 31,
            ("Stimulants", "Male", "with", "any"): 32,
            ("Stimulants", "Female", "with", "synthetic"): 37,
            ("Stimulants", "Male", "with", "synthetic"): 38,
            ("Cocaine", "Female", "overall", "overall"): 43,
            ("Cocaine", "Male", "overall", "overall"): 44,
            ("Cocaine", "Female", "with", "any"): 46,
            ("Cocaine", "Male", "with", "any"): 47,
            ("Cocaine", "Female", "with", "synthetic"): 52,
            ("Cocaine", "Male", "with", "synthetic"): 53,
            ("Psychostimulants", "Female", "overall", "overall"): 58,
            ("Psychostimulants", "Male", "overall", "overall"): 59,
            ("Psychostimulants", "Female", "with", "any"): 61,
            ("Psychostimulants", "Male", "with", "any"): 62,
            ("Psychostimulants", "Female", "with", "synthetic"): 67,
            ("Psychostimulants", "Male", "with", "synthetic"): 68,
            ("Benzodiazepines", "Female", "overall", "overall"): 73,
            ("Benzodiazepines", "Male", "overall", "overall"): 74,
            ("Benzodiazepines", "Female", "with", "any"): 76,
            ("Benzodiazepines", "Male", "with", "any"): 77,
            ("Benzodiazepines", "Female", "with", "synthetic"): 82,
            ("Benzodiazepines", "Male", "with", "synthetic"): 83,
            ("Antidepressants", "Female", "overall", "overall"): 88,
            ("Antidepressants", "Male", "overall", "overall"): 89,
            ("Antidepressants", "Female", "with", "any"): 91,
            ("Antidepressants", "Male", "with", "any"): 92,
            ("Antidepressants", "Female", "with", "synthetic"): 97,
            ("Antidepressants", "Male", "with", "synthetic"): 98,
        }

    },
    'Number Drug OD, 15-24 Years': {
        "valid_rows": 66,
        "indices": {
            ("Overall", "Female"): 1,
            ("Overall", "Male"): 2,
            ("Any opioid", "Female"): 4,
            ("Any opioid", "Male"): 5,
            ("Prescription opioids", "Female", "overall", "overall"): 7,
            ("Prescription opioids", "Male", "overall", "overall"): 8,
            ("Prescription opioids", "Female", "with", "synthetic"): 10,
            ("Prescription opioids", "Male", "with", "synthetic"): 11,
            ("Synthetic opioids", "Female", "overall", "overall"): 13,
            ("Synthetic opioids", "Male", "overall", "overall"): 14,
            ("Heroin", "Female", "overall", "overall"): 16,
            ("Heroin", "Male", "overall", "overall"): 17,
            ("Heroin", "Female", "with", "synthetic"): 19,
            ("Heroin", "Male", "with", "synthetic"): 20,
            ("Stimulants", "Female", "overall", "overall"): 22,
            ("Stimulants", "Male", "overall", "overall"): 23,
            ("Stimulants", "Female", "with", "any"): 25,
            ("Stimulants", "Male", "with", "any"): 26,
            ("Stimulants", "Female", "with", "synthetic"): 28,
            ("Stimulants", "Male", "with", "synthetic"): 29,
            ("Cocaine", "Female", "overall", "overall"): 31,
            ("Cocaine", "Male", "overall", "overall"): 32,
            ("Cocaine", "Female", "with", "any"): 34,
            ("Cocaine", "Male", "with", "any"): 35,
            ("Cocaine", "Female", "with", "synthetic"): 37,
            ("Cocaine", "Male", "with", "synthetic"): 38,
            ("Psychostimulants", "Female", "overall", "overall"): 40,
            ("Psychostimulants", "Male", "overall", "overall"): 41,
            ("Psychostimulants", "Female", "with", "any"): 43,
            ("Psychostimulants", "Male", "with", "any"): 44,
            ("Psychostimulants", "Female", "with", "synthetic"): 46,
            ("Psychostimulants", "Male", "with", "synthetic"): 47,
            ("Benzodiazepines", "Female", "overall", "overall"): 49,
            ("Benzodiazepines", "Male", "overall", "overall"): 50,
            ("Benzodiazepines", "Female", "with", "any"): 52,
            ("Benzodiazepines", "Male", "with", "any"): 53,
            ("Benzodiazepines", "Female", "with", "synthetic"): 55,
            ("Benzodiazepines", "Male", "with", "synthetic"): 56,
            ("Antidepressants", "Female", "overall", "overall"): 58,
            ("Antidepressants", "Male", "overall", "overall"): 59,
            ("Antidepressants", "Female", "with", "any"): 61,
            ("Antidepressants", "Male", "with", "any"): 62,
            ("Antidepressants", "Female", "with", "synthetic"): 64,
            ("Antidepressants", "Male", "with", "synthetic"): 65,
        }

    },
    'Rate Drug OD, 15-24 Years': {
        "valid_rows": 66,
        "indices": {
            ("Overall", "Female"): 1,
            ("Overall", "Male"): 2,
            ("Any opioid", "Female"): 4,
            ("Any opioid", "Male"): 5,
            ("Prescription opioids", "Female", "overall", "overall"): 7,
            ("Prescription opioids", "Male", "overall", "overall"): 8,
            ("Prescription opioids", "Female", "with", "synthetic"): 10,
            ("Prescription opioids", "Male", "with", "synthetic"): 11,
            ("Synthetic opioids", "Female", "overall", "overall"): 13,
            ("Synthetic opioids", "Male", "overall", "overall"): 14,
            ("Heroin", "Female", "overall", "overall"): 16,
            ("Heroin", "Male", "overall", "overall"): 17,
            ("Heroin", "Female", "with", "synthetic"): 19,
            ("Heroin", "Male", "with", "synthetic"): 20,
            ("Stimulants", "Female", "overall", "overall"): 22,
            ("Stimulants", "Male", "overall", "overall"): 23,
            ("Stimulants", "Female", "with", "any"): 25,
            ("Stimulants", "Male", "with", "any"): 26,
            ("Stimulants", "Female", "with", "synthetic"): 28,
            ("Stimulants", "Male", "with", "synthetic"): 29,
            ("Cocaine", "Female", "overall", "overall"): 31,
            ("Cocaine", "Male", "overall", "overall"): 32,
            ("Cocaine", "Female", "with", "any"): 34,
            ("Cocaine", "Male", "with", "any"): 35,
            ("Cocaine", "Female", "with", "synthetic"): 37,
            ("Cocaine", "Male", "with", "synthetic"): 38,
            ("Psychostimulants", "Female", "overall", "overall"): 40,
            ("Psychostimulants", "Male", "overall", "overall"): 41,
            ("Psychostimulants", "Female", "with", "any"): 43,
            ("Psychostimulants", "Male", "with", "any"): 44,
            ("Psychostimulants", "Female", "with", "synthetic"): 46,
            ("Psychostimulants", "Male", "with", "synthetic"): 47,
            ("Benzodiazepines", "Female", "overall", "overall"): 49,
            ("Benzodiazepines", "Male", "overall", "overall"): 50,
            ("Benzodiazepines", "Female", "with", "any"): 52,
            ("Benzodiazepines", "Male", "with", "any"): 53,
            ("Benzodiazepines", "Female", "with", "synthetic"): 55,
            ("Benzodiazepines", "Male", "with", "synthetic"): 56,
            ("Antidepressants", "Female", "overall", "overall"): 58,
            ("Antidepressants", "Male", "overall", "overall"): 59,
            ("Antidepressants", "Female", "with", "any"): 61,
            ("Antidepressants", "Male", "with", "any"): 62,
            ("Antidepressants", "Female", "with", "synthetic"): 64,
            ("Antidepressants", "Male", "with", "synthetic"): 65,
        }

    },
    'Rate OD by Demographic': {
        "valid_rows": 84,
        # TODO

    },
}

